### ISSUE TITLE
Hello Mr Ecotilla-Sanchez ,it seems that the plot-related functions are outta date

### ISSUE THREAD

**Issue by Vurgit** [ecotillasanchez/cosmic#1]
Hello Mr Ecotilla-Sanchez,it seems that the plot-related functions are out of date and it will cause errors in Matlab 2018b(other contents seem to be perfect) and some of the figures cannot show up.Would you please update the file a bit and restore it to its own perfection?Thanks a lot

**Comment by ecotillasanchez** [comment]
Hello Vurgit, could you please clarify what plot-related functions are the ones causing error? 

I just ran the example simulations **sim_case9.m** and **sim_case39.m** in MATLAB R2019b and all the default plots appear correctly without warning or error messages.

**Comment by Vurgit** [comment]
![ecs停电error](https://user-images.githubusercontent.com/56619134/69934050-cc062600-150b-11ea-8ad8-420834cc7117.png)
![ecs停电error2](https://user-images.githubusercontent.com/56619134/69934052-cc9ebc80-150b-11ea-998f-a37335c0b101.png)
Thank you for answering me Mr Cotilla-Sanchez,the errors are shown as are in the pictures.Since I am using Matlab2018b in Chinese version,the general meaning of the errors is as follows:
----------------------------------------------------------
Warning: error when class matlab.graphics.primitive.canvas.Javacanvas defined event ButtonExited listener callback:
Error in settings
Attrbute'MonthsOfYear' has invalid default value:
Too many output parameters.
Error in getDatetimeSettings
Error matlab.graphics.controls.ToolbarController/createFadeInTimer
Error in matlab.graphics.controls.ToolbarController/get.FadeInTimer
Error in matlab.graphics.controls.ToolbarController/hideToolbar
Error in matlab.graphics.controls.ToolbarController/handleMouseExited
Error in matlab.graphics.controls.ToolbarController>@(e,d)obj.handleMouseExited(e,d) 
-----------------------------------------------------------
There seem to be repetitive errors of the same kind below,probably resulted from a function called several times to draw a chain of pictures.It may not be a huge bug but some pictures may not be plotted correctly.Since I havent used MATLAB in English version the translation of the error reports may be slightly discrepant.

**Comment by ecotillasanchez** [comment]
Sorry that I cannot debug those in Chinese. It seems like it probably is affecting some datetime formatting internal function on the Java code upon translating. I am unable to do any changes in the code to support that at this time.
